from app import db
from app.models import *
import os

school = School(name="Petrov_petr", password=os.environ.get("ADMIN_PASSWORD"))
#db.session.add(school)
#group = Group(name="10B", school=school)
group1 = Group(name="10K", school=school)
group2 = Group(name="9S", school=school)
group3 = Group(name="7T", school=school)
db.session.add(group1)
db.session.add(group2)
db.session.add(group3)
student1 = Student(name="человек_Q", group=group1)
student2 = Student(name="человек_W", group=group1)
student3 = Student(name="человек_E", group=group2)
student4 = Student(name="человек_R", group=group2)
student5= Student(name="человек_T", group=group2)
student6 = Student(name="человек_U", group=group3)
student7= Student(name="человек_P", group=group3)
student8 = Student(name="человек_A", group=group3)
student9= Student(name="человек_D", group=group3)
student10 = Student(name="человек_F", group=group3)
db.session.add(student1)
db.session.add(student2)
db.session.add(student3)
db.session.add(student4)
db.session.add(student5)
db.session.add(student6)
db.session.add(student7)
db.session.add(student8)
db.session.add(student9)
db.session.add(student10)
db.session.commit()

