from app import db
from app.models import *
import os

school1 = School(name="toruteva_309_11", password="abcdef321")#6Г
school2 = School(name="luk_419_10201", password="shaof9081")  #10Э
school3 = School(name="kodirova_625", password="star77tap")   #5Г
db.session.add(school1)
db.session.add(school2)
db.session.add(school3)
# group = Group(name="10B", school=school)
group1 = Group(name="6Г", school=school1)
group2 = Group(name="10Э", school=school2)
group3 = Group(name="5Г", school=school3)
db.session.add(group1)
db.session.add(group2)
db.session.add(group3)
student1 = Student(name="Антонов Глеб Ильич", group=group1)
student2 = Student(name="Белоногова Вера Дмитриевна", group=group1)
student3 = Student(name="Воловиков Дмитрий Сергеевич", group=group1)
student4 = Student(name="Гусакова-Станюкович Евгения Игоревна", group=group1)
student5 = Student(name="Долгополова София Сергеевна", group=group1)
student6 = Student(name="Евдокимов Владимир Русланович", group=group1)
student7 = Student(name="Евсеева Евгения Алексеевна", group=group1)
student8 = Student(name="Ельников Василий Александрович", group=group1)
student9 = Student(name="Жарков Александр Николаевич", group=group1)
student10 = Student(name="Колесникова Мария Александровна", group=group1)
student11 = Student(name="Колотушкина Василиса Михайловна", group=group1)
student12 = Student(name="Крюкова Варвара Максимовна", group=group1)
student13 = Student(name="Маленко Владимир Владимирович", group=group1)
student14 = Student(name="Мусатов Алексей Александрович", group=group1)
student15 = Student(name="Никулин Михаил Олегович", group=group1)
student16 = Student(name="Новикова Алиса Сергеевна", group=group1)
student17 = Student(name="Паронян Елена Владиславовна", group=group1)
student18 = Student(name="Пескова Анна Александровна", group=group1)
student19 = Student(name="Поннучами Амил Дживанантхам", group=group1)
student20 = Student(name="Потапова Екатерина Дмитриевна", group=group1)
student21 = Student(name="Почивалин Александр Денисович", group=group1)
student22 = Student(name="Рыков Георгий Алексеевич", group=group1)
student23 = Student(name="Терещенко Алина Алексеевна", group=group1)
student24 = Student(name="Тоста Полина Анджеевна", group=group1)
student25 = Student(name="Хоконова Сабрина Алимовна", group=group1)
student26 = Student(name="Хромых Глеб Сергеевич", group=group1)
student27 = Student(name="Чесноков Егор Александрович", group=group1)
student28 = Student(name="Чукавова Юлия Дмитриевна", group=group1)
student29 = Student(name="Яковлева Майя Олеговна", group=group1)
student30 = Student(name="Андреева Ольга Дмитриевна", group=group2)
student31 = Student(name="Белов Тимофей Николаевич", group=group2)
student32 = Student(name="Викулин Григорий Александрович", group=group2)
student33 = Student(name="Воловиков Николай Сергеевич", group=group2)
student34 = Student(name="Габараев Артур Александрович", group=group2)
student35 = Student(name="Ерофтеев Иван Дмитриевич", group=group2)
student36 = Student(name="Колесников Егор Александрович", group=group2)
student37 = Student(name="Кузнецова Софья Анатольевна", group=group2)
student38 = Student(name="Кулабухов Константин Владимирович", group=group2)
student39 = Student(name="Леонов Андрей Андреевич", group=group2)
student40 = Student(name="Лычёв Арсений Сергеевич", group=group2)
student41 = Student(name="Любчак Максим Эдуардович", group=group2)
student42 = Student(name="Медведева Елизавета Михайловна", group=group2)
student43 = Student(name="Сайфуллин Арслан Маратович", group=group2)
student44 = Student(name="Фрайман Михаил Романович", group=group2)
student45 = Student(name="Чурин Данила Дмитриевич", group=group2)
student46 = Student(name="Шилкин Максим Олегович", group=group2)
student47 = Student(name="Березина Наталия Николаевна", group=group3)
student48 = Student(name="Буканчиков Федор Андреевич", group=group3)
student49 = Student(name="Волкова Вероника Александровна", group=group3)
student50 = Student(name="Грибанова София Олеговна", group=group3)
student51 = Student(name="Жемчужникова Дарья Владиславовна", group=group3)
student52 = Student(name="Зарецкий Арсений Александрович", group=group3)
student53 = Student(name="Золотухина Елизавета Олеговна", group=group3)
student54 = Student(name="Кашина Елизавета Максимовна", group=group3)
student55 = Student(name="Килин Глеб Андреевич", group=group3)
student56 = Student(name="Кузьмина Ника Александровна", group=group3)
student57 = Student(name="Лоншакова Ева Андреевна", group=group3)
student58 = Student(name="Лященко Алиса Александровна", group=group3)
student59 = Student(name="Магомедова Месед Магомедовна", group=group3)
student60 = Student(name="Магомедов Руслан Магомедович", group=group3)
student61 = Student(name="Мироненко Юрий Антонович", group=group3)
student62 = Student(name="Петросова Алина Эдуардовна", group=group3)
student63 = Student(name="Потапов Никита Андреевич", group=group3)
student64 = Student(name="Потапов Николай Алексеевич", group=group3)
student65 = Student(name="Приходченко Ксения Кирилловна", group=group3)
student66 = Student(name="Пуллес Рябов Рикардо", group=group3)
student67 = Student(name="Пупков Антон Дмитриевич", group=group3)
student68 = Student(name="Скрыпник Григорий Артемович", group=group3)
student69 = Student(name="Суханова Софья Александровна", group=group3)
student70 = Student(name="Теплякова Елизавета Николаевна", group=group3)
student71 = Student(name="Терешенкова Мария Дмитриевна", group=group3)
student72 = Student(name="Троицкий Александр Михайлович", group=group3)
student73 = Student(name="Федосенко Даниил Сергеевич", group=group3)
student74 = Student(name="Чернозубенко Михаил Дмитриевич", group=group3)

db.session.add(student1)
db.session.add(student2)
db.session.add(student3)
db.session.add(student4)
db.session.add(student5)
db.session.add(student6)
db.session.add(student7)
db.session.add(student8)
db.session.add(student9)
db.session.add(student10)
db.session.add(student11)
db.session.add(student12)
db.session.add(student13)
db.session.add(student14)
db.session.add(student15)
db.session.add(student16)
db.session.add(student17)
db.session.add(student18)
db.session.add(student19)
db.session.add(student20)
db.session.add(student21)
db.session.add(student22)
db.session.add(student23)
db.session.add(student24)
db.session.add(student25)
db.session.add(student26)
db.session.add(student27)
db.session.add(student28)
db.session.add(student29)
db.session.add(student30)
db.session.add(student31)
db.session.add(student32)
db.session.add(student33)
db.session.add(student34)
db.session.add(student35)
db.session.add(student36)
db.session.add(student37)
db.session.add(student38)
db.session.add(student39)
db.session.add(student40)
db.session.add(student41)
db.session.add(student42)
db.session.add(student43)
db.session.add(student44)
db.session.add(student45)
db.session.add(student46)
db.session.add(student47)
db.session.add(student48)
db.session.add(student49)
db.session.add(student50)
db.session.add(student51)
db.session.add(student52)
db.session.add(student53)
db.session.add(student54)
db.session.add(student55)
db.session.add(student56)
db.session.add(student57)
db.session.add(student58)
db.session.add(student59)
db.session.add(student60)
db.session.add(student61)
db.session.add(student62)
db.session.add(student63)
db.session.add(student64)
db.session.add(student65)
db.session.add(student66)
db.session.add(student67)
db.session.add(student68)
db.session.add(student69)
db.session.add(student70)
db.session.add(student71)
db.session.add(student72)
db.session.add(student73)
db.session.add(student74)
db.session.commit()
